### PR TITLE
UI-task

### PR DESCRIPTION
**Pull request by Tanushree-coder**
Issue: 317

#### Short description of what this resolves:

added figma link

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Tanushree-coder** [comment]
@zorione mam pls review

**Comment by Tanushree-coder** [comment]
@zorione mam pls tell if I need to make any changes

**Comment by zorione** [comment]
I will review it by noon.

**Comment by Tanushree-coder** [comment]
> I will review it by noon.

ok, sure mam.

**Comment by Tanushree-coder** [comment]
@zorione  mam , done with the changes, pls review now!

**Comment by Manav1410** [comment]
marked some changes in figma comments

**Comment by Tanushree-coder** [comment]
> marked some changes in figma comments

done ..

**Pull request merged**
