### PR TITLE
Added flow diagram for issue #2

### PR DESCRIPTION
**Pull request by ArshpreetS**
Issue: #2 

## Short description of what this resolves:

- Created a file of user experience task 1.md.
- Added the link to the user flow diagram.
- Added some questions that could be asked in the survey.

### CODE REVIEW

**Comment by ArshpreetS** [comment]
I tried adding a bit of questions that could be asked. Let me know if any improvements can be made because I am struggling to find any

**Comment by karrocks** [comment]
The user flow can be more elaborate highlighting the steps the user will take exactly going through the app. Good attempt though!

**Comment by ArshpreetS** [comment]
When I was watching the video you provided on user flow diagram. It asked to be precise but can you confirm how I should keep in mind while creating user flow diagram next time?

**Comment by karrocks** [comment]
This flow is correct but is missing some steps which will be required for while developing an actual app. Just think exactly about the precise steps user will take one after the other while moving through the app and define states accordingly. Keep designing😇

**Pull request merged**
