### PR TITLE
Create shreya.txt

### PR DESCRIPTION
**Pull request by shreya-0508**
Issue: 2

#### Short description of what this resolves:

flow to find a roomie

#### Changes proposed in this pull request and/or Screenshots of changes:

-flowchart to find a roomie
-
-

### CODE REVIEW

**Comment by shreya-0508** [comment]
I have updated my design file kindly review it
here is the link : https://www.figma.com/file/v04FjmAIgllDoMFjqF29ee/shreya_ux?node-id=0%3A1

**Comment by shreya-0508** [comment]
I have updated my design file kindly review it
here is the link : https://www.figma.com/file/v04FjmAIgllDoMFjqF29ee/shreya_ux?node-id=0%3A1

**Comment by shreya-0508** [comment]
@zorione 
I have updated my design file kindly review it
here is the link : https://www.figma.com/file/v04FjmAIgllDoMFjqF29ee/shreya_ux?node-id=0%3A1

**Comment by zorione** [comment]
It's fine now. Create a new pull request.

**Comment by shreya-0508** [comment]
@zorione  request has been closed though I have created pr yesterday in time

**Pull request closed without merging**
